name: Build and deploy Node.js app to Azure Web App - BackEndChatBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Debug npm
        run: npm config list
      
      - name: Show versions
        run: |
          node -v
          npm -v
      
      - name: Install dependencies
        run: |
          npm ci
          npm ls --depth=0
      
      - name: Build with debug
        run: |
          npm run build --if-present --verbose
        env:
          CI: true
          DEBUG: '*'
      
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3F5AD2C49D1C44519D5F57A0F51CB0F8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6470B685F4CE45038D97385F42B93A64 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A1C3EB265A9541EB86FDD4AB103BAC2D }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TeamsBot'
          slot-name: 'Production'
          package: './release.zip'


          

